### ISSUE TITLE
Maybe port for another editor?

### ISSUE THREAD

**Issue by Alexey-T** [mitchvm/tabnav#1]
CudaText has the Python API, consider to make the port, pls.

http://wiki.freepascal.org/CudaText
http://wiki.freepascal.org/CudaText_API

**Comment by mitchvm** [comment]
I appreciate that you're trying to generate interest for your project, @Alexey-T, and I commend you for undertaking it. However, I don't have time to implement this plugin for another editor right now. A quick glance at the API suggests it wouldn't be a trivial exercise to port it.

Good luck with your project. Perhaps some time in the future I might reconsider.
